#!/usr/bin/env bash

sudo apt-get update
sudo apt-get install -y git

# brew wants a confirmation before continuing
echo -ne '\n' | /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

sudo apt-get install -y software-properties-common
sudo apt-get update
sudo apt-get install -y ctop tmux direnv

mkdir ~/.zsh
git clone https://github.com/tarjoilija/zgen.git "${HOME}/.zgen"

brew install git hub
brew install neovim
brew install asdf chruby ruby-install
brew install fzf the_silver_searcher
brew install jq direnv
brew install --with-jansson --HEAD universal-ctags/universal-ctags/universal-ctags
$(brew --prefix fzf)/install

# asdf

asdf plugin-add postgres
asdf plugin-add python
asdf plugin-add nodejs https://github.com/asdf-vm/asdf-nodejs.git
bash ~/.asdf/plugins/nodejs/bin/import-release-team-keyring

asdf install nodejs 12.10.0
asdf install postgres 12.1

# vim/tmux plugin install

./setup/neovim.sh
~/.tmux/plugins/tpm/bin/install_plugins

setup/rust

brew install zsh && chsh -s "$(which zsh)"

function configure_user() {
  echo "Coniguring user $1"
  sudo -E su "$1"
  pushd ~

  #cp -r "$DOTFILES_PATH"/.config ~
  #cp -r "$DOTFILES_PATH"/.tmux ~
  #cp    "$DOTFILES_PATH"/.zshrc ~
  #cp    "$DOTFILES_PATH"/.zsh_plugins ~
  #cp    "$DOTFILES_PATH"/.zsh/ag_helpers ~/.zsh
  #cp    "$DOTFILES_PATH"/.tmux.conf ~
  #cp    "$DOTFILES_PATH"/.gitignore_global ~
  #cp    "$DOTFILES_PATH"/.gitconfig ~
  #cp    "$DOTFILES_PATH"/.bash_login ~
  #cp    "$DOTFILES_PATH"/.pryrc ~


  popd
  exit
}
