#!/usr/bin/env bash

sudo apt-get install -y software-properties-common

sudo add-apt-repository -y ppa:neovim-ppa/stable
sudo add-apt-repository -y ppa:git-core/ppa

sudo apt-get update

sudo apt-get install -y neovim git ctop zsh tmux chruby ruby-install silversearcher-ag

./setup/linux-fzf

export DOTFILES_PATH="$1"

function configure_user() {
  echo "Coniguring user $1"
  sudo -E su "$1"
  pushd ~

  cp -r "$DOTFILES_PATH"/.config ~
  cp    "$DOTFILES_PATH"/.zshrc ~
  cp    "$DOTFILES_PATH"/.tmux.conf ~
  cp    "$DOTFILES_PATH"/.gitignore_global ~
  cp    "$DOTFILES_PATH"/.gitconfig ~
  cp    "$DOTFILES_PATH"/.bash_login ~
  cp    "$DOTFILES_PATH"/.pryrc ~

  [ -d antigen ] || mkdir antigen
  curl -L git.io/antigen > ~/antigen/antigen.zsh

  nvim +silent +'PlugInstall --sync' +qall &> /dev/null < /dev/tty

  popd
  exit
}

for user in /home/*; do
  [ -d "$user" ] || continue
  configure_user "$user"
done
