#!/usr/bin/env bash

sudo apt-get install -y software-properties-common

sudo add-apt-repository -y ppa:neovim-ppa/stable
sudo add-apt-repository -y ppa:git-core/ppa

sudo apt-get update

sudo apt-get install -y neovim git ctop zsh tmux chruby ruby-install silversearcher-ag direnv

./setup/linux-fzf

export DOTFILES_PATH="$1"

function configure_user() {
  echo "Coniguring user $1"
  sudo -E su "$1"
  pushd ~

  mkdir ~/.zsh

  cp -r "$DOTFILES_PATH"/.config ~
  cp -r "$DOTFILES_PATH"/.tmux ~
  cp    "$DOTFILES_PATH"/.zshrc ~
  cp    "$DOTFILES_PATH"/.zsh_plugins ~
  cp    "$DOTFILES_PATH"/.zsh/ag_helpers ~/.zsh
  cp    "$DOTFILES_PATH"/.tmux.conf ~
  cp    "$DOTFILES_PATH"/.gitignore_global ~
  cp    "$DOTFILES_PATH"/.gitconfig ~
  cp    "$DOTFILES_PATH"/.bash_login ~
  cp    "$DOTFILES_PATH"/.pryrc ~

  git clone https://github.com/tarjoilija/zgen.git "${HOME}/.zgen"

  nvim +silent +'PlugInstall --sync' +qall &> /dev/null < /dev/tty

  ~/.tmux/plugins/tpm/bin/install_plugins

  popd
  exit
}

for user in /home/*; do
  [ -d "$user" ] || continue
  configure_user "$user"
done
