#!/usr/bin/env bash

echo "Reminder to myself: this hasn't been tested"

brew install tmux
brew install hub
brew install fzf
brew install chruby
brew install ruby-install
brew install neovim/neovim/neovim

git clone https://github.com/liaden/dotfiles ~/dotfiles

d ~/dotfiles

cp -r .config ~
cp .tmux.conf ~
cp .pryrc ~
cp .zshrc ~
cp .gitconfig ~

cd ~

git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
~/.tmux/plugins/tpm/bin/install_plugins

nvim +PlugInstall +qall

