#!/usr/bin/env bash

echo "Reminder to myself: this hasn't been tested"

brew install zsh bash pdsh
brew install direnv
brew install tmux reattach-to-user-namespace
brew install hub tig
brew install fzf
brew install chruby ruby-install
brew install neovim/neovim/neovim
brew install ctop htop glances
brew install the_silver_searcher
brew install xz
brew install wget jq lynx
brew install gnu-tar gnu-sed
brew install shellcheck yamllint kubeval
brew install fd
brew install asdf

asdf plugin-add ruby https://github.com/asdf-vm/asdf-ruby.git

nvim +PlugInstall +qall
