#!/usr/bin/env bash

curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --profile default -y
source "$HOME/.cargo/env"

# completions
mkdir ~/.zfunc
rustup completions zsh > ~/.zfunc/_rustup
rustup completions zsh cargo > ~/.zfunc/_cargo

# add components
rustup component add rust-src
rustup component add rustfmt
rustup component add clippy

cargo install -j "$(nproc)" cargo-watch
cargo install -j "$(nproc)" topgrade
cargo install -j "$(nproc)" cargo-update

# lang server for rust
mkdir -p ~/dev
pushd ~/dev || exit 1
git clone https://github.com/rust-analyzer/rust-analyzer
cd rust-analyzer || exit 1
cargo xtask install --server
popd || exit 1
