#!/usr/bin/env bash

curl https://sh.rustup.rs -sSf | sh

# completions
mkdir ~/.zfunc
rustup completions zsh > ~/.zfunc/_rustup
rustup completions zsh cargo > ~/.zfunc/_cargo

# add components
rustup component add rust-src
rustup component add rustfmt
rustup component add clippy

cargo install -j "$(nproc)" cargo-watch
cargo install -j "$(nproc)" topgrade
cargo install -j "$(nproc)" cargo-update

# lang server for rust
mkdir -p ~/dev
pushd ~/dev
git clone https://github.com/rust-analyzer/rust-analyzer; cd rust-analyzer
cargo xtask install --server
popd
